name: daily build with cron

on:
  schedule:
    - cron: '30 15 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        sudo npm install -g license-checker
    - name: Checkout example repository
      run: |
        mkdir test
        cd test
        git clone https://github.com/LGE-OSS/example
        cd example
        fosslight_scanner -p .
